//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentId { get; set; }
        public Nullable<int> PaymentAmount { get; set; }
        public Nullable<int> TokenID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string status { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual TokenDetail TokenDetail { get; set; }
    }
}
